from datetime import datetime, timezone

from cyberai.core.session import PentestSession, Severity

from .domains import group_by_domain

SEVERITY_EMOJI = {
    Severity.CRITICAL: "🔴",
    Severity.HIGH: "🟠",
    Severity.MEDIUM: "🟡",
    Severity.LOW: "🟢",
    Severity.INFO: "🔵",
}


def render_markdown(session: PentestSession) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    findings = session.findings

    critical = [f for f in findings if f.severity == Severity.CRITICAL]
    high = [f for f in findings if f.severity == Severity.HIGH]
    medium = [f for f in findings if f.severity == Severity.MEDIUM]
    low = [f for f in findings if f.severity == Severity.LOW]
    info = [f for f in findings if f.severity == Severity.INFO]

    lines = [
        "# CyberAI Pentest Report",
        "",
        f"**Target:** `{session.target}`  ",
        f"**Session ID:** `{session.session_id}`  ",
        f"**Generated:** {now}  ",
        f"**Status:** {session.state.value.upper()}",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        "| Severity | Count |",
        "|----------|-------|",
        f"| 🔴 Critical | {len(critical)} |",
        f"| 🟠 High     | {len(high)} |",
        f"| 🟡 Medium   | {len(medium)} |",
        f"| 🟢 Low      | {len(low)} |",
        f"| 🔵 Info     | {len(info)} |",
        f"| **Total**   | **{len(findings)}** |",
        "",
        "---",
        "",
        "## Findings",
        "",
    ]

    grouped = group_by_domain(findings)
    # Domain headings appear only once a scan actually spans more than one
    # surface; a plain network run renders exactly as it always has.
    split = len(grouped) > 1
    heading = "####" if split else "###"
    index = 0

    for domain, domain_findings in grouped.items():
        if split:
            lines += [f"### {domain} ({len(domain_findings)})", ""]

        for finding in domain_findings:
            index += 1
            emoji = SEVERITY_EMOJI.get(finding.severity, "⚪")
            lines += [
                f"{heading} {index}. {emoji} {finding.title}",
                "",
                f"**Severity:** {finding.severity.value}  ",
                f"**Target:** `{session.target}`  ",
                f"**Agent:** {finding.agent}  ",
                f"**Timestamp:** {finding.timestamp}",
                "",
                f"{finding.description}",
                "",
            ]
            if getattr(finding, "confidence", 1.0) < 1.0:
                lines.append(f"**Confidence:** {finding.confidence:.0%} ⚠️")
                lines.append("")
            if finding.cve:
                lines.append(f"**CVE:** `{finding.cve}`")
                lines.append("")
            if finding.data:
                lines.append(f"**Data:** `{finding.data}`")
                lines.append("")
            lines += ["---", ""]

    lines += [
        "## Summary",
        "",
        f"Total findings: {len(findings)}",
        f"Critical: {len(critical)} | High: {len(high)} | Medium: {len(medium)}",
    ]
    if split:
        lines.append(" | ".join(f"{d}: {len(v)}" for d, v in grouped.items()))
    lines += [
        "",
        "*Generated by CyberAI*",
    ]

    return "\n".join(lines)
